services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app:/app/src/
    env_file:
      - .env
    networks:
      - my-network

  redis:
    image: redis:7.4.2
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
#
#volumes:
#  app: