# Generated by Django 4.2.11 on 2025-02-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('type', models.CharField(choices=[('percent', 'Процент'), ('amount', 'Сумма'), ('fixed', 'Фиксированная цена')], max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение для типа скидки')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Минимальный остаток суммы при скидке на сумму')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('is_active', models.BooleanField(verbose_name='Активная ли скидка')),
                ('min_items', models.IntegerField(blank=True, null=True, verbose_name='min товаров')),
                ('max_items', models.IntegerField(blank=True, null=True, verbose_name='max товаров')),
                ('min_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Минимальная сумма')),
                ('max_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная сумма')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('type', models.CharField(choices=[('percent', 'Процент'), ('amount', 'Сумма'), ('fixed', 'Фиксированная цена')], max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение для типа скидки')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Минимальный остаток суммы при скидке на сумму')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('is_active', models.BooleanField(verbose_name='Активная ли скидка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
        ),
    ]
