# Generated by Django 4.2.11 on 2025-02-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsgroup',
            name='products',
            field=models.ManyToManyField(related_name='product_groups', to='products.product', verbose_name='Продукты'),
        ),
        migrations.AddField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='products.category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product_groups',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='discounts.productsgroup'),
        ),
        migrations.AddField(
            model_name='cartdiscount',
            name='product_groups',
            field=models.ManyToManyField(blank=True, related_name='cart_discounts', to='discounts.productsgroup', verbose_name='Группы товаров, для общей скидки на сочетания'),
        ),
    ]
