version: '3.8'

services:
  redis:
    image: redis:latest  # Используем официальный образ Redis
    container_name: redis  # Имя контейнера
    ports:
      - "6379:6379"  # Пробрасываем порт Redis на хост
    volumes:
      - redis_data:/data  # Сохраняем данные Redis в volume
    restart: always  # Автоматически перезапускать контейнер при сбоях

volumes:
  redis_data:  # Volume для хранения данных Redis