# Generated by Django 4.2.11 on 2025-02-27 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Продавец')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='Изображение')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавец',
            },
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('delivery_type', models.CharField(choices=[('STANDARD', 'Обычная доставка'), ('EXPRESS', 'Быстрая доставка'), ('FREE', 'Бесплатная доставка')], default='STANDARD', max_length=10, verbose_name='Тип доставки')),
                ('payment_type', models.CharField(choices=[('CARD', 'Онлайн картой'), ('CASH', 'Наличными')], default='CARD', max_length=50, verbose_name='Тип оплаты')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='products.product', verbose_name='Товар')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sellers.seller', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Товар продавца',
                'verbose_name_plural': 'Товары продавца',
                'unique_together': {('product', 'seller')},
            },
        ),
    ]
