# Generated by Django 4.2.11 on 2025-03-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Banner description'),
        ),
    ]
