# Generated by Django 4.2.11 on 2025-02-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('ordinary', 'Ordinary'), ('express', 'Express')], default='usually', max_length=10, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='The Сost of the delivery')),
                ('total_price_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total price for order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.CharField(choices=[('ordinary', 'Ordinary'), ('express', 'Express')], default='usually', max_length=10)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('pay', models.CharField(choices=[('online', 'Online cart'), ('someone', "Online from a random stranger's account.")], default='online', max_length=100)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total cost of the order')),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('not success', 'Not success')], default='not success', max_length=20)),
                ('card_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='card number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('error_message', models.CharField(blank=True, max_length=256, null=True, verbose_name='Payment error message')),
                ('payment_id', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='id for payment service')),
                ('cart_items', models.ManyToManyField(related_name='orders', to='cart.cartitem')),
            ],
        ),
    ]
